import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>gkScore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center">
        <div>
          <h1
            className="{`
        my-4 text-center
        font-bold text-5xl tracking-tight
        bg-gradient-to-r from-green-500 via-blue-500 to-pink-500
        bg-clip-text text-transparent 
    `}"
          >
            zkScore
          </h1>
          <div className="">
            <button
              className={`
              my-4
            bg-blue-500 hover:bg-yellow-500 
            p-3 rounded-full font-bold transition duration-300
            text-white
            `}
            >
              Connect Wallet
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
